// Bundle the TypeScript backend into a single self-contained CommonJS file the
// Electron main process can require(). esbuild inlines all node dependencies, so
// the packaged app needs no backend node_modules.
import { build } from 'esbuild';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const entry = path.resolve(here, '../../backend/src/server.ts');
const outfile = path.resolve(here, '../app/server.cjs');

await build({
  entryPoints: [entry],
  outfile,
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: 'node18',
  // node-pty is a native module: keep it external and load it from the app's
  // node_modules at runtime (electron-builder rebuilds it for the Electron ABI).
  external: ['node-pty'],
  logLevel: 'info',
  banner: { js: '/* JakIDE bundled backend — generated by build-backend.mjs */' },
});

console.log('Bundled backend ->', outfile);
